<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260619133357 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Change task.id and focus_time.id from auto-increment integer to UUID string';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE focus_time ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE focus_time ALTER id TYPE VARCHAR(36)');
        $this->addSql('ALTER TABLE focus_time ALTER task_id TYPE VARCHAR(36)');
        $this->addSql('ALTER TABLE task ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE task ALTER id TYPE VARCHAR(36)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE focus_time ALTER id TYPE INT');
        $this->addSql('ALTER TABLE focus_time ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE focus_time ALTER task_id TYPE INT');
        $this->addSql('ALTER TABLE task ALTER id TYPE INT');
        $this->addSql('ALTER TABLE task ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }
}
